### ISSUE TITLE
catch invalid `csv` files in pipeline step

### ISSUE THREAD

**Issue by simonsymhoven** [jenkinsci/nested-data-reporting-plugin#100]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

catch invalid csv files like

Level 1,Level 2,Level 3,incorrect,manually,accurate
Aktie,Aktie 1,Aktie 1 1,13,3,59
Aktie,Aktie,Aktie 1 2,31,48,9
Aktie,Aktie 1,Aktie 1 3,34,8,51
Derivat,Aktie 1,,1,2,3
Derivat,Derivat 2,,5,9,1
Not Found???,,,1,3,9

### Reproduction steps

.

### Expected Results

.

### Actual Results

.

**Comment by totocaca123** [comment]
new pull request catch problems.
Unfortunately, there is no logInfo function to output error messages (it's commented in code)
