### ISSUE TITLE
Add the possibility to change title 

### ISSUE THREAD

**Issue by totocaca123** [jenkinsci/nested-data-reporting-plugin#18]
### What feature do you want to see added?

When I add a report, on the left panel, title is always the same (and for multiple json file, I cannot distinguish)
![image](https://user-images.githubusercontent.com/42418580/185766418-373b4649-47dd-4060-9218-b04a9f426bf4.png)

The feature would consist in pipeline to define a title (like "My Metrics") to be seen on left panel

**Comment by simonsymhoven** [comment]
implement with #41
