### ISSUE TITLE
[URGENT] nested-data-reporting-plugin no longer works when updating echarts-api plugin from 5.4.0-3 to 5.4.0-4

### ISSUE THREAD

**Issue by nirman19** [jenkinsci/nested-data-reporting-plugin#197]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins v2.387.3, nested-data-reporting-plugin v5.2.1, echarts-api plugin 5.4.0-4
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

any

### Reproduction steps

update echarts-api plugin from 5.4.0-3 to 5.4.0-4

### Expected Results

nested-data-reporting-plugin must display trend graph

### Actual Results

nested-data-reporting-plugin no longer works

### Anything else?

Trend graph are no longer displayed.

Jobs using Nested Data Reporting plugin, are loaded with the following warning :
WARNING hudson.model.Run#onLoad: failed to load io.jenkins.plugins.reporter.ReportAction@1415692a from C:\Jenkins\jobs\test\jobs\test-nested-data-report\builds\10\build.xml
java.lang.NullPointerException

Jobs using Nested Data Reporting plugin, fails to run with the following error :
java.lang.ClassNotFoundException: org.eclipse.collections.impl.factory.Sets

Could you fix this [problem](https://github.com/jenkinsci/nested-data-reporting-plugin/pull/196), please?
Thanks in advance

**Comment by dragoudin** [comment]
which version of plugin are you using? (official release or last commit)?
Which version of jenkins?
I confirm this issue but i don't know if it comes from jenkins 3.400 or from plugin

**Comment by dragoudin** [comment]
I have these informations - 
This merge might solve the problem
Bump echarts-api from 5.4.0-3 to 5.4.0-4 #196

Need some tests with hpi version and release 5.2.2 in case of test is ok

**Comment by dragoudin** [comment]
Test with following hpi
https://ci.jenkins.io/job/Plugins/job/nested-data-reporting-plugin/job/master/

**Comment by dragoudin** [comment]
I tested, the latest master works. Needs to make a new release.
Unfortunately, historic graph seems to be lost

**Comment by totocaca123** [comment]
#196 caused some removed dependencies un echart plugin. Missing dependencies were added to this plugin. Issue is correcte
