### ISSUE TITLE
Add a total line on bottom of distribution area

### ISSUE THREAD

**Issue by totocaca123** [jenkinsci/nested-data-reporting-plugin#20]
### What feature do you want to see added?

Something like this
![image](https://user-images.githubusercontent.com/42418580/185810678-264a6584-93e0-443a-8365-646a2f40be39.png)

**Comment by simonsymhoven** [comment]
@totocaca123 I implemented this. For this I had to create the entire table manually, since this did not work with the previous implementation. For this reason I decided to show only the absolute numbers in the columns. The relative distribution is already in the last column anyway.

**Comment by simonsymhoven** [comment]
closed by #31
