### ISSUE TITLE
Add options for columns generation in Distribution area

### ISSUE THREAD

**Issue by totocaca123** [jenkinsci/nested-data-reporting-plugin#21]
### What feature do you want to see added?

In the example, it would be good to choose between the following possibilities:

- only 1 column (numbers or percent)
- 2 column (raw data + percent)
- 1 column (raw data with percent like   -  593 (17%))

This feature would save space (if there is multiple columns, data are displayed un percent so there is 2 times more columns)

**Comment by simonsymhoven** [comment]
with #31 and as described in #20 I had to create the entire table manually. For this reason I decided to show only the absolute numbers in the columns. The relative distribution is already in the last column anyway. Do you think this enhancement is still needed?

**Comment by totocaca123** [comment]
for each item, the best is to have only one column. Some people prefer see raw values, some others want percent, and some others both...

The best would be to set this in pipeline (to have an option like values : raw, percent, dual). By default, raw values are displayed
