### ISSUE TITLE
Add diff numbers relative to previous build

### ISSUE THREAD

**Issue by totocaca123** [jenkinsci/nested-data-reporting-plugin#49]
### What feature do you want to see added?

In the distribution arre, it woul be good in case of absolute date, to have diff ( like +10 or -10 if metric decreased)

![image](https://user-images.githubusercontent.com/42418580/188960055-83b575e8-ccb8-462d-a2ca-e9e93eda1932.png)

**Comment by simonsymhoven** [comment]
Do you have any idea how to display this? Like the `dual` display type -> 7513 (+134). or maybe it makes sense to add this reference metrics into a new table sheet like in #54 ?

**Comment by totocaca123** [comment]
I would say the best is to display like in warning ng plugin. In dual display, adding diff might be heayvy for view (3 data).
For percent, does diff number make sense (increase of xxx percent)

I suggest for absolute or relative, to display with same unit.
For dual, i dont know what is the best because which diff will be displayed (percent or raw number or both?)

Moreover, what is the best option:
- display diff automatically
- add an option in pipeline (showDelta=true?)
- add a checkbox somewhere to show or not
- add a tab in distribution area (compare to previous)

And for delta, if same implementation than warning ng is done, will the diff number will be cliclable and interactive

As well for overview:
- choice was made to show synthesis of all column.

Some people will prefer to see in oveeview the delta (like in warning next gen), other will prefer 1 pie chat , other multiple pie charts... 
I wonder if an option for overview type would be necessary in the futur (overviewType = delta or synthesis)

From usage, we have 4 report type (4 file format csv, json, yaml, xml).
Another idea is to make distinction at report type (for each format, define multiple kind of report - for example for csv, we can have current report focused only on data, report focused only on delta and metric evolution, report focused on limits (like if total reached limit or not)

For the plugin, depending on how complex is these options, it is either possible to create new options or define specific report format as reports might be very different.

**Comment by simonsymhoven** [comment]
close this issue, duplicate to #107
