### ISSUE TITLE
Multiple json files management

### ISSUE THREAD

**Issue by totocaca123** [jenkinsci/nested-data-reporting-plugin#58]
### What feature do you want to see added?

It's not a feature request but an open question:

- if we have multiple json files, multiple diagrams will be created (1 file = 1 report).

If we define same id and same report name in json file, all data are not merged and the plugin create multiple reports

How to force inside json file to indicate the right data set.
For example if I have 10 json files:

- File 1 to 4 go to report 1
- File 5 to 10 go to report 2
In the current design, 10 reports will be created
![image](https://user-images.githubusercontent.com/42418580/189479415-f03a8a86-3a4c-4e3c-9ad5-f793544ed3aa.png)

So for multiple file I see many options:

- Generate only 1 report (merging all data) but json files needs to be similar in columns
- Merge all files with same Id/Same report name? (json must be compatible each others or define 0 for undefined columns)

**Comment by simonsymhoven** [comment]
@totocaca123 Thanks for your effort and all the feedback! I appreciate it very much! Feel free to help with the development. I don't have too much time to spend on this :)

**Comment by simonsymhoven** [comment]
At the moment each json have to have a unique `id`.

**Comment by totocaca123** [comment]
> @totocaca123 Thanks for your effort and all the feedback! I appreciate it very much! Feel free to help with the development. I don't have too much time to spend on this :)

I'm available but my skills is quiet limited. I can work en file format, file examples, and minor features (could take few easy tasks).
Moreover, I find this plugin very interesting (similar to warning next generation). I tried to use warning plugin with csv to get the beautifull views, but it is impossible.
This plugin is similar to plot, but with a much more better interface. If the csv support (simply), this plugin could get lot of success

**Comment by totocaca123** [comment]
> At the moment each json have to have a unique `id`.

I tested (I copy/paste the example files). All my files have same ID and same report name. The plugin generates 1 report per file. So it seems that unique ID/report name is not corretly handled

**Comment by simonsymhoven** [comment]
> > At the moment each json have to have a unique `id`.
> 
> I tested (I copy/paste the example files). All my files have same ID and same report name. The plugin generates 1 report per file. So it seems that unique ID/report name is not corretly handled

That's true, I have to make sure, that each report has a unique id, otherwise the logic of this plugin won't work correct.
