### ISSUE TITLE
Improve file format handling

### ISSUE THREAD

**Issue by totocaca123** [jenkinsci/nested-data-reporting-plugin#64]
### What feature do you want to see added?

For the publishReport, I suggest to take inspiration from warning ng plugin.
For now the main format to support is csv, json, yaml (with specific syntax). Maybe some future files will be supported

- Generic CSV (simple file format accessible)
         publishReport(tools: [simpleCsv(id: 'customId', name: 'customName', pattern: '*.csv')])

- json + yaml + xml (plugin internal data format)
        publishReport(tools: [nativeJson(id: 'customId', name: 'customName', pattern: '*.json')])
        publishReport(tools: [nativeYaml(id: 'customId', name: 'customName', pattern: '*.yaml')])
        publishReport(tools: [nativeXml(id: 'customId', name: 'customName', pattern: '*.xml')])

In the future (with tool popularity increasing), other format might be supported (file from specific standards for metric data)

**Comment by simonsymhoven** [comment]
Thanks! Thats exactly what i am doing right now! I am now ready to take care of the merging of multiple reports..

**Comment by simonsymhoven** [comment]
@totocaca123 For now I have the following api:

```
publishReport name: "JSON Report", displayType: "dual", provider: json(pattern: "etc/*.json")
publishReport name: "XML Report", displayType: "dual", provider: xml(pattern: "etc/*.xml")
publishReport name: "YAML Report", displayType: "dual", provider: yaml(pattern: "etc/*.yaml")
```

the whole infrastructure is in place, now I have to merge the reports and plot the charts. And then let's see where errors still appear...

![Bildschirmfoto 2022-09-13 um 20 28 47](https://user-images.githubusercontent.com/26878018/189981759-480d4849-9d7b-49e5-968d-feff755c0858.png)
