### ISSUE TITLE
improve plugin description

### ISSUE THREAD

**Issue by totocaca123** [jenkinsci/nested-data-reporting-plugin#77]
### Describe your use-case which is not covered by existing documentation.

In the plugin description, adding keywords to improve plugin visibilité (like excel, metrics, data charts, pie charts, plot...). These changes would make more easy to find this plugin in Jenkins plugin search engine.

**Comment by simonsymhoven** [comment]
I updated the README and the index.jelly file, that will displayed in the installation manager of jenkins,  if you want to install this plugin. I also added some tags to the plugin description. 

Do you have any other suggestions?

If you want, I can add you as contributor. Then you are able to adjust this on your own.

**Comment by totocaca123** [comment]
Ok my contribution would be limited to documentation and test files

**Comment by totocaca123** [comment]
> I updated the README and the index.jelly file, that will displayed in the installation manager of jenkins,  if you want to install this plugin. I also added some tags to the plugin description. 
> 
> Do you have any other suggestions?
> 
> If you want, I can add you as contributor. Then you are able to adjust this on your own. 

Moreover, plugin search use keywords. Users type few keywords to find a plugin. So all keywords related to data visualisation... must be used to increase chances of this plugin to be downloaded

**Comment by simonsymhoven** [comment]
i invited you, so feel free to adjust the keywords and documentation :)
