### ISSUE TITLE
improve color management

### ISSUE THREAD

**Issue by totocaca123** [jenkinsci/nested-data-reporting-plugin#78]
### What feature do you want to see added?

When user doesnt provide colors, aleatory colors are created. Problem is when a data is associated with a random color, next build, will there be a new random color associated with a data ( it might be disturbing to see colors changing over builds)

I suggest définition of color thèmes (palette) which exists in Microsoft office. Association of a data with a color could be made aleatory, or according alphabetical order or number classification.
And option could be added (for example colorTheme = light or grayGradient, or rainbow....). Various theme exists and some themes could be copied from Microsoft office

**Comment by simonsymhoven** [comment]
@totocaca123 I agree with your second points, that's good idea.

But the first one I can not recreate. If I have a report step with a cdv provider and the cdv has obviously no colors, e.g.
```
publishReport name: "CSV Report", displayType: "dual", provider: csv(id: "csv-one", pattern: "etc/*.csv")
```

I get the following logging in the first build:

```
Searching for all files in '/Users/simonsymhoven/.jenkins/workspace/nested-m_master' that match the pattern 'etc/*.csv'
-> found 1 file
Successfully parsed file /Users/simonsymhoven/.jenkins/workspace/nested-m_master/etc/report.csv
First added report. Set ID='csv-one'
Add report with ID='csv-one'.
Add item wih ID='Aktie' to items.
Add item wih ID='Derivat' to items.
Add item wih ID='Not Found' to items.
Successfully added report with ID='csv-one'
Report has no colors! Try to find the colors of the previous report.
No previous report found. Will generate color palette.
```

So far so good.
Then I start a second build and the logging says:

```
Searching for all files in '/Users/simonsymhoven/.jenkins/workspace/nested-m_master' that match the pattern 'etc/*.csv'
-> found 1 file
Successfully parsed file /Users/simonsymhoven/.jenkins/workspace/nested-m_master/etc/report.csv
First added report. Set ID='csv-one'
Add report with ID='csv-one'.
Add item wih ID='Aktie' to items.
Add item wih ID='Derivat' to items.
Add item wih ID='Not Found' to items.
Successfully added report with ID='csv-one'
Report has no colors! Try to find the colors of the previous report.
Previous report has colors. Add it to this report.
```

And the colors are the same for both builds. 

If this is an issue, please describe what you did, then I can fix it :)

**Comment by totocaca123** [comment]
I was wondering if colors used to be changed all the time. When a color is set for first it is kept, so it's ok (no issue)


But it would be important to have some themes (kind of color consistencies...)

**Comment by simonsymhoven** [comment]
close this issue, duplicated to #106
